baseURL: "https://gambitproject.github.io"
languageCode: "en-us"
title: "Gambit: The package for computation in game theory"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  navColor: red
  images:
    - /images/gambit.png
  fonts:
    - name: "Lato"
      weights: [400, 900]
  navbarlogo:
    image: gambit.png
    link: /
  hero:
    title: Software tools for game theory.
    subtitle: Build, analyse, and explore finite extensive and strategic form games.
    image: gambit.png
    buttontext: Get started
    buttonlink: "https://gambitproject.readthedocs.io/en/stable/"
    description:
      - "Gambit is a set of software tools for doing computation on finite, noncooperative games in extensive or strategy form and a set of file formats for storing and communicating games to external tools."
      - "The Gambit Project was founded in the mid-1980s at the California Institute of Technology and to this day is actively developed by a community of contributors, with core development led by [The Alan Turing Institute](https://www.turing.ac.uk) as part of its project: [Automated analysis of strategic interactions](https://www.turing.ac.uk/research/research-projects/automated-analysis-strategic-interactions)."
    software_title: "Open source & free to use"
    software:
      - name: PyGambit
        description: "Python API providing access to Gambit's features."
        icon: python.png
        link: "https://gambitproject.readthedocs.io/en/stable/pygambit.html"
      - name: GUI
        description: "Visually construct games and investigate their main strategic features."
        icon: gui.png
        link: "https://gambitproject.readthedocs.io/en/stable/gui.html"
      - name: CLI
        description: "Command-line tools suitable for scripting or calling from other programs."
        icon: cli.png
        link: "https://gambitproject.readthedocs.io/en/stable/tools.html"
      # - name: LLM tools
      #   description: "üèóÔ∏è WIP: Construct extensive games using our language model framework."
      #   icon: llm.png
    whatgambit_title: "Gambit in a nutshell"
    whatgambit:
      - name: Non-cooperative finite games
        description: "Construct games in extensive or strategic form."
      - name: Equilibrium computation
        description: "Find pure and mixed-strategy Nash equilibria."
      - name: Econometric estimation
        description: "Fit quantal response and other structural models."
      - name: Interoperable with other tools
        description: "Read and write games in standard file formats."
      - name: Open source & extensible
        description: "Analyse your game models your way."
    # testimonials:
    #   - name: "Professor X"
    #     role: "Professor of Game Theory, University of Cambridge"
    #     quote: "Gambit is the gold standard for computational game theory. It has been a cornerstone of my research for over 20 years."
    #   - name: "Professor Y"
    #     role: "Professor of Computer Science, University of Oxford"
    #     quote: "Gambit provides powerful tools for analyzing complex strategic interactions, making it indispensable for my work in AI and game theory."
  navbar:
    # - title: Research
    #   url: /research/
    - title: Install
      url: "https://gambitproject.readthedocs.io/en/latest/install.html"
    - title: Documentation
      url: "https://gambitproject.readthedocs.io/en/stable/"
    - title: Team
      url: /team/
    - title: Citing
      url: /cite/
    - title: Info
      sublinks:
        - title: GitHub
          url: "https://github.com/gambitproject/gambit"
        - title: PyGambit on PyPI
          url: "https://pypi.org/project/pygambit/"
  team:
    title: "The Gambit Development Team"
    description: "Gambit is developed and maintained by a core team at The Alan Turing Institute, with contributions from the wider community."
    members:
      - name: "Theodore Turocy"
        affiliations: 
          - "The Alan Turing Institute"
          - "University of East Anglia"
        role: "Theme Lead: Game theory and collective decision making in foundational AI research"
        image: team/ted.png
        link: "https://tturocy.github.io/"
      - name: "Rahul Savani"
        affiliations: 
          - "The Alan Turing Institute"
          - "University of Liverpool"
        role: "Theme lead: Automated Analysis of Strategic Interactions"
        image: team/rahul.png
        link: "https://www.turing.ac.uk/people/external-researchers/rahul-savani"
      - name: "Daniel Kadnikov"
        affiliations: 
          - "The Alan Turing Institute"
        role: "Research Associate"
        image: team/daniel.png
        link: "https://www.turing.ac.uk/people/daniel-kadnikov"
      - name: "Ed Chalstrey"
        affiliations:
          - "The Alan Turing Institute"
        role: "Research Software Engineer"
        image: team/ed.png
        link: "https://edchalstrey.com/"
      - name: "Stephen Pasteris"
        affiliations: 
          - "The Alan Turing Institute"
        role: "Research Associate"
        image: team/stephen.jpeg
        link: "https://ieeexplore.ieee.org/author/37086404209"
      # - name: "Yongzhao Wang"
      #   affiliations: 
      #     - "The Alan Turing Institute"
      #   role: "Former Research Associate"
      #   image: team/yongzhao.png
      #   link: "https://sites.google.com/umich.edu/yongzhao-wang/"
    # research:
    #   title: "Selected Research Projects Using Gambit"
    #   # description: "A variety of research projects using Gambit are currently underway, exploring new methods for game-theoretic analysis, applications in AI, and the development of novel algorithms."
    #   projects:
    #     - title: "Automated analysis of strategic interactions"
    #       institution: "The Alan Turing Institute"
    #       description: "Creating the tools to support strategic reasoning about interactions among human and automated agents in complex and changing environments."
    #       link: "https://www.turing.ac.uk/research/research-projects/automated-analysis-strategic-interactions"
  footer:
    logo: gambit.png
    socialmediatitle:
    socialmedia:
      - link: https://twitter.com/thegambitproj
        icon: discourse
      - link: https://github.com/gambitproject/gambit
        icon: github

